# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

before_all do
   update_fastlane
   unlock_keychain(path: 'login',
               password: ENV['FL_UNLOCK_KEYCHAIN_PASSWORD'],
            set_default: true
   )

end

platform :ios do
  desc "Build ad hoc distributable for QA (currently using AppCenter)"

    lane :beta_release do
        puts ENV['MATCH_PASSWORD']
        api_key =  app_store_connect_api_key(
          key_id: "W9B9PYU6CZ",
          issuer_id: "69a6de86-32d6-47e3-e053-5b8c7c11a4d1",
          key_filepath: "./fastlane/AuthKey_W9B9PYU6CZ.p8",
          in_house: false # optional but may be required if using match/sigh
      )

      match(
        type:"adhoc", 
        app_identifier: ["com.contextual.airbnb"],
        force_for_new_devices: true, 
        verbose: true
      )

      increment_build_number(
        build_number: Time.now.to_i.to_s
      )

      gym(
        scheme:"airbnb-main",
    	  export_method:"ad-hoc",
        export_options: {
          provisioningProfiles: {
            "com.contextual.airbnb" => "match AdHoc com.contextual.airbnb"
          },
          clean: true,
          xcargs: "-UseNewBuildSystem=YES"
        }
      )
      
      commit = last_git_commit
      changelog = changelog_from_git_commits(commits_count: 10, pretty: '• %s', merge_commit_filtering: 'exclude_merges')
    end





end
