platform :ios,'15.0'

workspace 'airbnb-main'

config = use_frameworks!

install! 'cocoapods',
  :warn_for_unused_master_specs_repo => false

target 'airbnb-main' do
  # Pods for airbnb-main
  pod "Contextual", podspec:"https://repo.contextu.al/artifactory/contextual/ios/podspec/dev/Contextual.podspec"

  pod 'AppCenter'
  pod 'AppCenter/Distribute'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
